import fs from 'node:fs/promises';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const projectRoot = path.join(root, 'hyperframes-workflow-kit', 'projects', 'demoText-f1-20s');
const variantsRoot = path.join(projectRoot, 'production', 'variants');
const sourceGsap = path.join(root, 'experiments', 'E10-style-probes', 'variants', 'A-handdrawn-board', 'assets', 'gsap.min.js');
const sourceAudio = path.join(projectRoot, 'input', 'narration-excerpt.wav');

const styles = [
  {id: 'editorial-data-report', label: '编辑型数据简报', tone: '#d9274d', bg: '#f4f7f4', kind: 'report'},
  {id: 'apple-clean-product', label: '苹果式清爽产品', tone: '#0071e3', bg: '#f5f5f7', kind: 'apple'},
  {id: 'pixel-card-platform-ui', label: '像素卡片 UI', tone: '#0647b8', bg: '#fff4d8', kind: 'pixel'},
  {id: 'magazine-collage-cards', label: '轻量杂志拼贴', tone: '#c9483e', bg: '#f4eadb', kind: 'magazine'},
  {id: 'monochrome-cyber-editorial-cards', label: '黑白赛博编辑', tone: '#a7ff3c', bg: '#080808', kind: 'cyber'},
  {id: 'handdrawn-workflow-tutorial', label: '手绘流程教程', tone: '#d81e45', bg: '#fbfaf4', kind: 'hand'},
  {id: 'data-hud-narration', label: '深色数据 HUD 口播', tone: '#57e6ff', bg: '#071017', kind: 'hud'},
];

const commonCss = `
@font-face{font-family:"Microsoft YaHei";src:local("Microsoft YaHei")}@font-face{font-family:"PingFang SC";src:local("PingFang SC")}@font-face{font-family:"Noto Sans SC";src:local("Noto Sans SC")}@font-face{font-family:"Noto Serif SC";src:local("Noto Serif SC")}@font-face{font-family:"Comic Sans MS";src:local("Comic Sans MS")}@font-face{font-family:"SFMono-Regular";src:local("SFMono-Regular")}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}body{font-family:"Microsoft YaHei","PingFang SC","Noto Sans SC",Arial,sans-serif;letter-spacing:0}#main{position:relative;width:720px;height:1280px;overflow:hidden}#fill{position:absolute;inset:0}.scene{position:absolute;inset:0;overflow:hidden}.world{position:absolute;inset:0}.ambient{position:absolute;pointer-events:none}.title{position:absolute;z-index:4;margin:0;font-size:76px;line-height:1.05;font-weight:900;letter-spacing:0;white-space:pre-line}.subtitle{position:absolute;z-index:4;margin:0;font-size:28px;line-height:1.35}.surface{position:absolute;z-index:3}.item,.layer{opacity:0}.item,.layer,.caption-line,#conclusion{will-change:transform,opacity}#conclusion{position:absolute;z-index:8}.caption-rail{position:absolute;z-index:9;left:42px;right:42px;bottom:54px;min-height:112px;padding:18px 22px;border:2px solid #151515;background:rgba(255,255,255,.94);color:#151515}.caption-label{margin:0 0 8px;font:700 14px/1.2 ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:.08em;opacity:.72}.caption-line{position:absolute;left:22px;right:22px;margin:0;font-size:27px;line-height:1.25;font-weight:700;opacity:0}.caption-line[data-kind="generated-summary"]{font-weight:900}.micro{font:700 15px/1.2 ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:.08em}.chip{display:inline-flex;align-items:center;min-height:36px;padding:0 14px;border:2px solid currentColor;font-size:20px;font-weight:800}.rule{position:absolute;height:4px;transform-origin:left center}.bar,.meter{transform-origin:left center}.draw-path{fill:none}.noise{position:absolute;inset:0;opacity:.08;pointer-events:none;background-image:repeating-radial-gradient(circle at 20% 30%,rgba(0,0,0,.35) 0 1px,transparent 1px 4px);background-size:7px 7px}.grid{position:absolute;inset:0;opacity:.16;background-image:linear-gradient(currentColor 1px,transparent 1px),linear-gradient(90deg,currentColor 1px,transparent 1px);background-size:72px 72px}.safe-line{position:absolute;left:36px;right:36px;height:1px;background:currentColor;opacity:.25}
`;

const styleCss = {
  report: `
body{background:#dfe5e1;color:#0c0d0d}#fill{background:#f4f7f4}.report-top{position:absolute;left:42px;right:42px;top:42px;display:flex;justify-content:space-between;border-bottom:2px solid #0c0d0d;padding-bottom:12px;color:#0c0d0d}.report-title{left:42px;top:128px;width:620px;color:#0c0d0d}.report-title .accent{color:#d9274d}.report-sub{left:44px;top:315px;color:#55605b}.report-surface{left:42px;right:42px;top:390px;height:480px;padding:26px;border:2px solid #0c0d0d;background:#fff}.report-surface .surface-heading{margin:0 0 22px;font-size:23px;font-weight:900}.report-items{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.report-item{min-height:90px;padding:16px;border-top:8px solid #d9274d;background:#eef1ee}.report-item:nth-child(2){border-color:#ffd526}.report-item:nth-child(3){border-color:#347fb8}.report-item:nth-child(4){border-color:#bfc4c2}.report-layers{position:absolute;left:42px;right:42px;top:875px}.report-layer{display:grid;grid-template-columns:150px 1fr 100px;align-items:center;gap:16px;margin:10px 0;color:#0c0d0d}.report-layer .track{height:18px;background:#d5dad7;overflow:hidden}.report-layer .bar{height:100%;background:#d9274d}.report-layer:nth-child(2) .bar{background:#ffd526}.report-layer:nth-child(3) .bar{background:#347fb8}.report-conclusion{left:42px;right:42px;bottom:180px;padding:20px 24px;border-left:8px solid #d9274d;background:#fff;color:#0c0d0d;font-size:33px;font-weight:900}
`,
  apple: `
body{background:#d9dde3;color:#1d1d1f}#fill{background:#f5f5f7}.apple-top{position:absolute;left:48px;right:48px;top:42px;display:flex;justify-content:space-between;color:#6e6e73}.apple-title{left:48px;top:116px;width:620px;color:#1d1d1f;font-size:72px}.apple-title .accent{color:#0071e3}.apple-sub{left:50px;top:305px;color:#6e6e73}.apple-window{left:48px;right:48px;top:388px;height:480px;border:1px solid rgba(0,0,0,.14);border-radius:28px;background:rgba(255,255,255,.82);box-shadow:0 24px 60px rgba(58,69,82,.18);overflow:hidden}.window-bar{height:54px;padding:16px 20px;border-bottom:1px solid rgba(0,0,0,.08);color:#6e6e73}.window-dot{display:inline-block;width:12px;height:12px;margin-right:8px;border-radius:50%;background:#c8ccd0}.apple-items{display:flex;flex-wrap:wrap;gap:14px;padding:34px}.apple-item{min-width:240px;padding:20px;border-radius:18px;background:#eef1f5;border:1px solid rgba(0,0,0,.08);color:#1d1d1f}.apple-layer-stack{position:absolute;left:48px;right:48px;top:860px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.apple-layer{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;border:1px solid rgba(0,0,0,.1);border-radius:18px;background:#fff;color:#1d1d1f;box-shadow:0 10px 24px rgba(58,69,82,.08)}.apple-layer .meter{width:130px;height:10px;border-radius:10px;background:#0071e3}.apple-conclusion{left:48px;right:48px;bottom:175px;padding:22px 26px;border-radius:22px;background:#d7f1ff;color:#1d1d1f;font-size:31px;font-weight:800}
`,
  pixel: `
body{background:#e3d6b7;color:#111}#fill{background:#fff4d8}.pixel-top{position:absolute;left:32px;right:32px;top:30px;height:56px;padding:16px 18px;background:#0647b8;color:#fff;border:4px solid #111;box-shadow:8px 8px 0 #111;display:flex;justify-content:space-between}.pixel-title{left:34px;top:132px;width:640px;color:#111;font-size:68px;text-shadow:5px 5px 0 #f7c600}.pixel-sub{left:38px;top:310px;color:#0647b8;font-weight:800}.pixel-quest{left:32px;right:32px;top:380px;height:470px;padding:24px;border:5px solid #111;background:#fff7e8;box-shadow:10px 10px 0 #111}.pixel-quest-head{display:flex;justify-content:space-between;padding-bottom:18px;border-bottom:4px solid #111;color:#0647b8;font-size:24px;font-weight:900}.pixel-items{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:22px}.pixel-item{padding:22px 16px;border:4px solid #111;background:#f7c600;box-shadow:5px 5px 0 #111;font-size:22px;font-weight:900}.pixel-item:nth-child(2){background:#26b84a}.pixel-item:nth-child(3){background:#e4484c;color:#fff}.pixel-item:nth-child(4){background:#c9c9c9}.pixel-layers{position:absolute;left:32px;right:32px;top:840px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.pixel-layer{height:108px;padding:12px;border:4px solid #111;background:#fff7e8;box-shadow:4px 4px 0 #111}.pixel-layer .meter{height:12px;margin-top:15px;background:#0647b8}.pixel-conclusion{left:32px;right:32px;bottom:175px;padding:18px;border:5px solid #111;background:#0647b8;color:#fff;box-shadow:8px 8px 0 #111;font-size:29px;font-weight:900}
`,
  magazine: `
body{background:#d7c5ab;color:#201d1a}#fill{background:#f4eadb}.mag-top{position:absolute;left:38px;right:38px;top:36px;display:flex;justify-content:space-between;color:#7c322c}.mag-title{left:42px;top:112px;width:620px;color:#201d1a;font-family:Georgia,"Noto Serif SC",serif;font-size:72px}.mag-title .accent{color:#c9483e}.mag-sub{left:46px;top:310px;color:#7c322c}.mag-paper{left:44px;right:44px;top:380px;height:470px;padding:28px;border:2px solid #201d1a;background:#fffaf1;box-shadow:14px 14px 0 rgba(32,29,26,.2);transform:rotate(-1deg)}.mag-paper:before{content:"";position:absolute;left:18px;top:-14px;width:180px;height:28px;background:rgba(243,204,109,.75);transform:rotate(-4deg)}.mag-items{display:flex;flex-direction:column;gap:14px;margin-top:32px}.mag-item{padding:18px 20px;border:2px solid #201d1a;background:#f8f1e7;box-shadow:5px 5px 0 rgba(32,29,26,.18);font-size:23px;font-weight:800}.mag-item:nth-child(2){background:#dff2ed}.mag-item:nth-child(3){background:#f7dfd2}.mag-layers{position:absolute;left:46px;right:46px;top:840px;display:flex;gap:12px;align-items:flex-end}.mag-layer{flex:1;min-height:110px;padding:16px;border:2px solid #201d1a;background:#fffaf1;box-shadow:6px 6px 0 rgba(32,29,26,.2);transform:rotate(-2deg)}.mag-layer:nth-child(2){transform:rotate(2deg);background:#dff2ed}.mag-layer:nth-child(3){transform:rotate(-1deg);background:#f7dfd2}.mag-conclusion{left:46px;right:46px;bottom:175px;padding:19px 24px;border:3px solid #201d1a;background:#c9483e;color:#fffaf1;font-size:30px;font-weight:900;box-shadow:8px 8px 0 rgba(32,29,26,.24)}
`,
  cyber: `
body{background:#030303;color:#f2f2f2}#fill{background:#080808}.cyber-grid{color:#a7ff3c}.cyber-top{position:absolute;left:38px;right:38px;top:34px;display:flex;justify-content:space-between;color:#a7ff3c}.cyber-title{left:38px;top:116px;width:644px;color:#fff;font-size:75px;line-height:.98}.cyber-title .accent{color:#a7ff3c}.cyber-sub{left:42px;top:310px;color:#8a8a8a}.cyber-hero{left:38px;right:38px;top:382px;height:458px;padding:28px;border:1px solid rgba(255,255,255,.28);background:#111;overflow:hidden}.cyber-hero .cross{position:absolute;right:24px;top:26px;width:84px;height:84px;border:1px solid #a7ff3c;border-radius:50%}.cyber-hero .cross:before,.cyber-hero .cross:after{content:"";position:absolute;background:#a7ff3c}.cyber-hero .cross:before{left:41px;top:-10px;width:1px;height:102px}.cyber-hero .cross:after{top:41px;left:-10px;width:102px;height:1px}.cyber-items{position:absolute;left:28px;right:28px;bottom:24px;display:grid;grid-template-columns:1fr 1fr;gap:12px}.cyber-item{padding:16px;border:1px solid rgba(255,255,255,.22);background:#171717;color:#b0b0b0}.cyber-item strong{display:block;color:#fff;font-size:26px}.cyber-layers{position:absolute;left:38px;right:38px;top:840px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.cyber-layer{min-height:115px;padding:14px;border:1px solid rgba(255,255,255,.22);background:#111;color:#b0b0b0}.cyber-layer strong{display:block;color:#fff;font-size:20px}.cyber-layer .meter{height:8px;margin-top:18px;background:#a7ff3c}.cyber-conclusion{left:38px;right:38px;bottom:175px;padding:20px 24px;border:1px solid #a7ff3c;background:#111;color:#fff;font-size:30px;font-weight:900}
`,
  hand: `
body{background:#d7d2c4;color:#151515}#fill{background:#fbfaf4}.hand-top{position:absolute;left:40px;right:40px;top:34px;display:flex;justify-content:space-between;color:#151515}.hand-title{left:42px;top:112px;width:620px;color:#151515;font-family:"Comic Sans MS","Noto Sans SC",sans-serif;font-size:72px;transform:rotate(-1deg)}.hand-title .accent{color:#d81e45}.hand-sub{left:44px;top:310px;color:#3d777b}.hand-browser{left:40px;right:40px;top:380px;height:260px;border:4px solid #151515;border-radius:18px;background:#fff;box-shadow:8px 8px 0 rgba(21,21,21,.14)}.hand-browser .browser-bar{height:42px;border-bottom:3px solid #151515;padding:10px 14px}.hand-browser .browser-dot{display:inline-block;width:14px;height:14px;margin-right:8px;border:2px solid #151515;border-radius:50%;background:#d81e45}.hand-items{position:absolute;left:70px;right:70px;top:690px;display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.hand-item{padding:16px;border:3px solid #151515;background:#ddf4f5;box-shadow:5px 5px 0 rgba(21,21,21,.15);font-size:22px;font-weight:800}.hand-item:nth-child(2){background:#fff}.hand-rail{position:absolute;left:50px;right:50px;top:850px;height:88px;border-top:4px solid #151515;border-bottom:4px solid #151515;display:flex;align-items:center;justify-content:space-around}.hand-node{width:36px;height:36px;border:3px solid #151515;border-radius:50%;background:#fff}.hand-node.active{background:#d81e45}.hand-path{position:absolute;left:90px;top:800px;width:540px;height:100px}.hand-system{position:absolute;left:190px;right:190px;top:930px;height:78px;padding:12px;border:4px solid #151515;background:#fff;box-shadow:7px 7px 0 rgba(21,21,21,.14);text-align:center}.hand-conclusion{left:42px;right:42px;bottom:175px;padding:18px 22px;border:4px solid #151515;background:#d81e45;color:#fff;font-size:30px;font-weight:900;box-shadow:7px 7px 0 rgba(21,21,21,.14)}
`,
  hud: `
body{background:#02080d;color:#d8f7ff}#fill{background:#071017}.hud-grid{color:#57e6ff}.hud-top{position:absolute;left:36px;right:36px;top:34px;display:flex;justify-content:space-between;color:#57e6ff}.hud-title{left:38px;top:112px;width:640px;color:#d8f7ff;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:62px;line-height:1.02}.hud-title .accent{color:#57e6ff}.hud-sub{left:40px;top:310px;color:#83a7b4;font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.hud-core{left:36px;right:36px;top:380px;height:430px;border:1px solid rgba(87,230,255,.6);background:rgba(8,24,32,.86);padding:28px}.hud-core .orb{position:absolute;left:250px;top:80px;width:160px;height:160px;border:2px solid #57e6ff;border-radius:50%;box-shadow:0 0 0 18px rgba(87,230,255,.06),0 0 0 42px rgba(87,230,255,.035)}.hud-core .orb:before,.hud-core .orb:after{content:"";position:absolute;background:#57e6ff}.hud-core .orb:before{left:79px;top:-38px;width:2px;height:236px}.hud-core .orb:after{top:79px;left:-38px;width:236px;height:2px}.hud-items{position:absolute;left:28px;right:28px;bottom:22px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.hud-item{padding:12px;border:1px solid rgba(87,230,255,.38);background:#0c1d26;color:#83a7b4;font:700 14px/1.3 ui-monospace,SFMono-Regular,Consolas,monospace}.hud-item strong{display:block;color:#d8f7ff;font-size:24px}.hud-layers{position:absolute;left:36px;right:36px;top:840px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.hud-layer{display:grid;grid-template-columns:1fr;align-content:center;gap:8px;padding:12px 14px;min-height:78px;border:1px solid rgba(87,230,255,.3);background:#0b1820;color:#83a7b4;font:700 15px/1.2 ui-monospace,SFMono-Regular,Consolas,monospace}.hud-layer .meter{height:9px;background:#57e6ff}.hud-conclusion{left:36px;right:36px;bottom:175px;padding:19px 22px;border:1px solid #57e6ff;background:#0c1d26;color:#d8f7ff;font:800 26px/1.3 ui-monospace,SFMono-Regular,Consolas,monospace}
`,
};

const markup = {
  report: `<div class="report-top micro"><span>AI SYSTEMS / CASE 01</span><span>20 SEC STUDY</span></div><h1 id="headline" class="title report-title">会拖节点\n不等于懂<span class="accent">系统</span></h1><p id="subline" class="subtitle report-sub">界面把复杂性藏在按钮后面</p><div id="surface" class="surface report-surface"><p class="surface-heading">PLATFORM SURFACE / EASY ENTRY</p><div class="report-items"><div class="item report-item"><b>低代码</b><span class="micro">LOW CODE</span></div><div class="item report-item"><b>无代码</b><span class="micro">NO CODE</span></div><div class="item report-item"><b>AI 平台</b><span class="micro">MODEL ACCESS</span></div><div class="item report-item"><b>工作流工具</b><span class="micro">WORKFLOW</span></div></div></div><div class="report-layers"><div class="layer report-layer"><b>模型调用</b><div class="track"><div class="bar"></div></div><span class="micro">01</span></div><div class="layer report-layer"><b>API 连接</b><div class="track"><div class="bar"></div></div><span class="micro">02</span></div><div class="layer report-layer"><b>向量库</b><div class="track"><div class="bar"></div></div><span class="micro">03</span></div><div class="layer report-layer"><b>工具链调度</b><div class="track"><div class="bar"></div></div><span class="micro">04</span></div></div><div id="conclusion" class="report-conclusion">上手更快，排错更难。</div>`,
  apple: `<div class="apple-top"><span class="micro">SYSTEM / OVERVIEW</span><span class="micro">01—20</span></div><h1 id="headline" class="title apple-title">会拖节点\n不等于懂<span class="accent">系统</span></h1><p id="subline" class="subtitle apple-sub">把复杂问题藏进一个干净的界面</p><div id="surface" class="surface apple-window"><div class="window-bar"><span class="window-dot"></span><span class="window-dot"></span><span class="window-dot"></span><span class="micro">WORKFLOW BUILDER</span></div><div class="apple-items"><div class="item apple-item"><b>低代码</b><p class="micro">快速开始</p></div><div class="item apple-item"><b>AI 平台</b><p class="micro">一键调用</p></div><div class="item apple-item"><b>工作流</b><p class="micro">连接节点</p></div><div class="item apple-item"><b>结果</b><p class="micro">看起来完成</p></div></div></div><div class="apple-layer-stack"><div class="layer apple-layer"><span>模型调用 / API</span><div class="meter"></div></div><div class="layer apple-layer"><span>向量库 / 上下文</span><div class="meter"></div></div><div class="layer apple-layer"><span>权限 / 状态管理</span><div class="meter"></div></div><div class="layer apple-layer"><span>失败 / 维护</span><div class="meter"></div></div></div><div id="conclusion" class="apple-conclusion">界面很轻，系统并不轻。</div>`,
  pixel: `<div class="pixel-top"><span>WORLD 01 / SYSTEM QUEST</span><span>LV.20</span></div><h1 id="headline" class="title pixel-title">会拖节点\n不等于懂系统</h1><p id="subline" class="subtitle pixel-sub">任务：找到隐藏的工程底座</p><div id="surface" class="surface pixel-quest"><div class="pixel-quest-head"><span>WORKFLOW MENU</span><span>4 ITEMS</span></div><div class="pixel-items"><div class="item pixel-item">低代码</div><div class="item pixel-item">AI 平台</div><div class="item pixel-item">API 连接</div><div class="item pixel-item">工具链</div></div></div><div class="pixel-layers"><div class="layer pixel-layer"><b>MODEL</b><div class="meter"></div></div><div class="layer pixel-layer"><b>DATA</b><div class="meter"></div></div><div class="layer pixel-layer"><b>STATE</b><div class="meter"></div></div><div class="layer pixel-layer"><b>FAIL</b><div class="meter"></div></div></div><div id="conclusion" class="pixel-conclusion">DEMO CLEAR / PRODUCT LOCKED</div>`,
  magazine: `<div class="mag-top micro"><span>FIELD NOTE / 01</span><span>AI WORKFLOW</span></div><h1 id="headline" class="title mag-title">会拖节点\n不等于懂<span class="accent">系统</span></h1><p id="subline" class="subtitle mag-sub">一张漂亮的流程图，背后还有多少层？</p><div id="surface" class="surface mag-paper"><p class="micro">CUT-OUT / EASY ENTRY</p><div class="mag-items"><div class="item mag-item">低代码 / 无代码</div><div class="item mag-item">AI 平台 / 工作流</div><div class="item mag-item">按钮 / 节点 / 结果</div></div></div><div class="mag-layers"><div class="layer mag-layer"><b>模型</b><span class="micro">CALL</span></div><div class="layer mag-layer"><b>接口</b><span class="micro">CONNECT</span></div><div class="layer mag-layer"><b>数据</b><span class="micro">CONTEXT</span></div><div class="layer mag-layer"><b>状态</b><span class="micro">MAINTAIN</span></div></div><div id="conclusion" class="mag-conclusion">漂亮的 Demo，不等于可维护的产品。</div>`,
  cyber: `<div class="grid cyber-grid"></div><div class="cyber-top micro"><span>WORKFLOW SYSTEM / 001</span><span>STATUS: EXPOSE</span></div><h1 id="headline" class="title cyber-title">会拖节点\n不等于懂<span class="accent">系统</span></h1><p id="subline" class="subtitle cyber-sub">THE INTERFACE IS NOT THE ARCHITECTURE</p><div id="surface" class="surface cyber-hero"><div class="micro">SURFACE LAYER / EASY ENTRY</div><div class="cross"></div><div class="cyber-items"><div class="item cyber-item"><strong>LOW CODE</strong>包装复杂度</div><div class="item cyber-item"><strong>AI PLATFORM</strong>隐藏调用链</div><div class="item cyber-item"><strong>WORKFLOW</strong>节点化操作</div><div class="item cyber-item"><strong>DEMO</strong>一次跑通</div></div></div><div class="cyber-layers"><div class="layer cyber-layer"><strong>MODEL</strong><span>01 / CALL</span><div class="meter"></div></div><div class="layer cyber-layer"><strong>API</strong><span>02 / LINK</span><div class="meter"></div></div><div class="layer cyber-layer"><strong>DATA</strong><span>03 / CONTEXT</span><div class="meter"></div></div><div class="layer cyber-layer"><strong>STATE</strong><span>04 / MAINTAIN</span><div class="meter"></div></div></div><div id="conclusion" class="cyber-conclusion">THE DEMO IS NOT THE SYSTEM.</div>`,
  hand: `<div class="hand-top micro"><span>SOURCE / WORKFLOW NOTE</span><span>01 / 05</span></div><h1 id="headline" class="title hand-title">会拖节点\n不等于懂<span class="accent">系统</span></h1><p id="subline" class="subtitle hand-sub">把一个“简单按钮”拆开看看</p><div id="surface" class="surface hand-browser"><div class="browser-bar"><span class="browser-dot"></span><span class="browser-dot"></span><span class="browser-dot"></span><span class="micro">workflow.example / start</span></div><div class="micro" style="padding:42px 26px">低代码 · 无代码 · AI 平台 · 工作流工具</div></div><svg class="hand-path" viewBox="0 0 540 100"><path class="draw-path" d="M20 18 C130 18 150 82 270 82 S410 18 520 18" stroke="#151515" stroke-width="4" stroke-linecap="round"/></svg><div class="hand-items"><div class="item hand-item">模型调用</div><div class="item hand-item">API 连接</div><div class="item hand-item">向量库</div><div class="item hand-item">工具链调度</div></div><div class="hand-rail"><span class="hand-node active"></span><span class="hand-node"></span><span class="hand-node"></span><span class="hand-node"></span><span class="hand-node"></span></div><div class="hand-system"><span class="micro">工程底座 / SYSTEM BASE</span><div class="micro">真正难的是失败、状态和维护</div></div><div id="conclusion" class="hand-conclusion">会拖节点，不等于懂系统。</div>`,
  hud: `<div class="grid hud-grid"></div><div class="hud-top micro"><span>VOICE / LOCKED EXCERPT</span><span>00:20.000</span></div><h1 id="headline" class="title hud-title">会拖节点\n不等于懂<span class="accent">系统</span></h1><p id="subline" class="subtitle hud-sub">SURFACE / HIDDEN COMPLEXITY</p><div id="surface" class="surface hud-core"><div class="micro">AGENT RUNTIME / SIGNAL CORE</div><div class="orb"></div><div class="hud-items"><div class="item hud-item"><strong>4</strong>隐藏层</div><div class="item hud-item"><strong>01</strong>入口</div><div class="item hud-item"><strong>?</strong>失败</div><div class="item hud-item"><strong>0%</strong>可见</div></div></div><div class="hud-layers"><div class="layer hud-layer"><span>MODEL CALL</span><div class="meter"></div><span>01 / 04</span></div><div class="layer hud-layer"><span>API LINK</span><div class="meter"></div><span>02 / 04</span></div><div class="layer hud-layer"><span>VECTOR CONTEXT</span><div class="meter"></div><span>03 / 04</span></div><div class="layer hud-layer"><span>STATE / MAINTAIN</span><div class="meter"></div><span>04 / 04</span></div></div><div id="conclusion" class="hud-conclusion">可见的是按钮，决定产品的是系统。</div>`,
};

const captionMarkup = `<div class="caption-rail"><p class="caption-label">NARRATION / LOCKED EXCERPT</p><p id="cap-1" class="caption-line" data-kind="exact-source">第一，平台把系统的复杂性给隐藏起来。</p><p id="cap-2" class="caption-line" data-kind="exact-source">低代码、无代码、AI平台、工作流工具，</p><p id="cap-3" class="caption-line" data-kind="exact-source">把模型调用、API连接、向量库、工具链调度流程</p><p id="cap-4" class="caption-line" data-kind="generated-summary">会拖节点，不等于懂系统。</p></div>`;

const htmlFor = (style) => `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=720, initial-scale=1"><title>${style.label} · demoText · 20s</title><style>${commonCss}${styleCss[style.kind]}</style></head><body><div id="main" data-composition-id="main" data-start="0" data-duration="20" data-width="720" data-height="1280"><div id="fill"></div><div id="scene" class="clip scene" data-start="0" data-duration="20" data-track-index="0"><div class="world">${markup[style.kind]}${captionMarkup}<div class="noise"></div></div></div><audio id="narration" class="clip" src="./assets/narration.wav" data-start="0" data-duration="20" data-track-index="4"></audio><script src="./assets/gsap.min.js"></script><script>
(() => {
  const tl = gsap.timeline({paused:true});
  tl.fromTo('#headline',{y:28,opacity:0},{y:0,opacity:1,duration:.62,ease:'power3.out'},.25);
  tl.fromTo('#subline',{y:16,opacity:0},{y:0,opacity:1,duration:.38,ease:'power2.out'},.92);
  tl.fromTo('#surface',{y:34,scale:.96,opacity:0},{y:0,scale:1,opacity:1,duration:.72,ease:'power3.out'},2.5);
  tl.fromTo('.item',{y:22,scale:.96,opacity:0},{y:0,scale:1,opacity:1,duration:.52,ease:'power2.out',stagger:.42},4.0);
  tl.to('#surface',{scale:1.012,duration:.9,yoyo:true,repeat:1,ease:'power2.inOut'},6.15);
  tl.fromTo('.layer',{x:-24,opacity:0},{x:0,opacity:1,duration:.46,ease:'power2.out',stagger:.38},8.4);
  if(document.querySelector('.bar')) tl.fromTo('.bar',{scaleX:0},{scaleX:1,duration:.7,ease:'power2.out',stagger:.15},9.0);
  if(document.querySelector('.meter')) tl.fromTo('.meter',{scaleX:0},{scaleX:1,duration:.7,ease:'power2.out',stagger:.16},9.0);
  tl.to('.world',{y:-6,scale:1.006,duration:1.4,yoyo:true,repeat:1,ease:'power2.inOut'},11.0);
  tl.fromTo('#conclusion',{y:22,scale:.97,opacity:0},{y:0,scale:1,opacity:1,duration:.58,ease:'power3.out'},14.9);
  const captionTimes=[['#cap-1',0.05,3.7],['#cap-2',3.75,8.3],['#cap-3',8.35,14.0],['#cap-4',14.05,20.1]];
  captionTimes.forEach(([selector,start,end])=>{tl.fromTo(selector,{y:10,opacity:0},{y:0,opacity:1,duration:.18,ease:'power2.out'},start);tl.to(selector,{y:-6,opacity:0,duration:.16,ease:'power2.in'},end);});
  document.querySelectorAll('.draw-path').forEach((path)=>{const len=path.getTotalLength();path.style.strokeDasharray=len;path.style.strokeDashoffset=len;tl.to(path,{strokeDashoffset:0,duration:1.1,ease:'power2.out'},5.0);});
  if(document.querySelector('.hand-node')) tl.to('.hand-node',{scale:1.16,duration:.2,yoyo:true,repeat:1,ease:'power2.inOut',stagger:.55},8.2);
  tl.to('#main',{x:0,y:-4,scale:1.006,duration:1.4,ease:'power2.inOut'},17.2);
  tl.set('#timeline-sentinel',{opacity:0},20);
  window.__timelines=window.__timelines||{};window.__timelines.main=tl;
})();</script><div id="timeline-sentinel"></div></div></body></html>`;

const writeJson = (file, value) => fs.writeFile(file, `${JSON.stringify(value, null, 2)}\n`, 'utf8');

await fs.mkdir(variantsRoot, {recursive: true});
for (const style of styles) {
  const dir = path.join(variantsRoot, style.id);
  await fs.mkdir(path.join(dir, 'assets'), {recursive: true});
  await fs.mkdir(path.join(dir, 'snapshots'), {recursive: true});
  await fs.writeFile(path.join(dir, 'index.html'), htmlFor(style), 'utf8');
  await fs.copyFile(sourceGsap, path.join(dir, 'assets', 'gsap.min.js'));
  await fs.copyFile(sourceAudio, path.join(dir, 'assets', 'narration.wav'));
  await writeJson(path.join(dir, 'hyperframes.json'), {
    '$schema': 'https://hyperframes.heygen.com/schema/hyperframes.json',
    registry: 'https://raw.githubusercontent.com/heygen-com/hyperframes/main/registry',
    composition: {id: 'main', width: 720, height: 1280, fps: 30, duration: 20},
    style: style.id,
  });
  await writeJson(path.join(dir, 'style-selection.json'), {
    schemaVersion: 'autovideo-style-selection/v1',
    projectId: `demoText-f1-20s-${style.id}`,
    baseStyleId: style.id,
    framePreset: null,
    addons: [],
    registryItems: [],
    blueprints: style.kind === 'hand' ? ['spatial-pan-stations'] : [],
    motionRules: style.kind === 'hand' ? ['viewport-change', 'svg-path-draw', 'css-marker-patterns'] : style.kind === 'report' ? ['stat-bars-and-fills', 'svg-path-draw'] : style.kind === 'magazine' ? ['card-morph-anchor', 'css-marker-patterns'] : ['viewport-change', 'stat-bars-and-fills'],
    status: 'draft',
    approvedBy: null,
    notes: 'User explicitly requested approximately 20 seconds per F1 style. Official data-chart, flowchart-vertical, caption-editorial-emphasis, and grain-overlay were evaluated first. Their motion grammar was adapted where appropriate; the blocks were not mounted because their dimensions/content do not match this shared portrait comparison, and the official grain component uses an infinite CSS animation forbidden by this project determinism contract.',
    receipts: [
      {source: 'demo/f1/HF_风格与动效库_分享包搭建说明 (1).md', kind: 'user-provided', license: 'unknown'},
      {source: 'vendor/hyperframes/registry/registry.json', kind: 'official', license: 'Apache-2.0'},
      {source: 'vendor/hyperframes/skills/hyperframes-animation/rules-index.md', kind: 'official', license: 'Apache-2.0'},
    ],
  });
  await writeJson(path.join(dir, `${style.id}.motion.json`), {
    duration: 20,
    assertions: [
      {kind: 'appearsBy', selector: '#headline', bySec: 1.2},
      {kind: 'appearsBy', selector: '#surface', bySec: 3.6},
      {kind: 'appearsBy', selector: '#conclusion', bySec: 16.2},
      {kind: 'before', a: '#surface', b: '#conclusion'},
      {kind: 'staysInFrame', selector: '.caption-rail'},
      {kind: 'keepsMoving', withinSelector: '.world', maxStaticSec: 2.2},
    ],
  });
  await fs.writeFile(path.join(dir, 'package.json'), JSON.stringify({private:true,scripts:{lint:'npx --yes hyperframes@0.7.59 lint',check:'npx --yes hyperframes@0.7.59 check --snapshots',snapshot:'npx --yes hyperframes@0.7.59 snapshot --at 0,3.5,8.5,14.5,19.8',render:'npx --yes hyperframes@0.7.59 render --quality draft --output render.mp4'}}, null, 2) + '\n', 'utf8');
}

console.log(JSON.stringify({project: projectRoot, variants: styles.map((style) => style.id), duration: 20, resolution: '720x1280', audio: 'input/narration-excerpt.wav'}, null, 2));




