export const toolRegistry = [
  {
    id: 'local-source-index',
    name: 'Local Source Index',
    repo: null,
    license: 'project-local adapter',
    role: '在本机登记来源、SHA-256、类型与版权状态，不上传内容。',
    integration: 'ready',
  },
  {
    id: 'open-notebook',
    name: 'Open Notebook',
    repo: 'https://github.com/lfnovo/open-notebook',
    license: 'MIT',
    role: '素材库、PDF/网页/音视频导入、检索、Transformation 与引用式笔记。',
    integration: 'adapter-needed',
  },
  {
    id: 'ragflow',
    name: 'RAGFlow',
    repo: 'https://github.com/infiniflow/ragflow',
    license: 'Apache-2.0',
    role: '大规模复杂文档解析、混合检索、重排与可追溯引用。',
    integration: 'optional-service',
  },
  {
    id: 'storm',
    name: 'STORM / Co-STORM',
    repo: 'https://github.com/stanford-oval/storm',
    license: 'MIT',
    role: '多视角研究、引文式大纲和人工参与的知识地图。只生成研究包。',
    integration: 'optional-service',
  },
  {
    id: 'gpt-researcher',
    name: 'GPT Researcher',
    repo: 'https://github.com/assafelovic/gpt-researcher',
    license: 'Apache-2.0',
    role: '对本地资料和 Web 缺口做有引用的补充研究。不能直接产出锁定口播。',
    integration: 'optional-service',
  },
  {
    id: 'codex-cli',
    name: 'Codex CLI',
    repo: 'https://github.com/openai/codex',
    license: 'Apache-2.0',
    role: '按项目 AGENTS.md 和结构化 schema 生成证据、口播、分镜或执行 HyperFrames 阶段。',
    integration: 'ready',
  },
  {
    id: 'deterministic-planning',
    name: 'Deterministic Planning Baseline',
    repo: null,
    license: 'project-local adapter',
    role: '从 NarrationLock、alignment 与模板机器合同生成可重放的 scene/cue/Graph IR；LLM 只作为可选 enrichment。',
    integration: 'ready',
  },
  {
    id: 'promptfoo',
    name: 'Promptfoo',
    repo: 'https://github.com/promptfoo/promptfoo',
    license: 'MIT',
    role: '文稿提示词、RAG 事实约束和模型升级的回归测试。',
    integration: 'ready-offline-ci',
  },
  {
    id: 'cosyvoice14',
    name: 'CosyVoice 预设 14',
    repo: 'https://github.com/FunAudioLLM/CosyVoice',
    license: 'Apache-2.0 code; speaker rights needs review',
    role: '中文女 / FP32 / stream=false / speed 1.03 / seed 7 的可复现本地配音。',
    integration: 'ready',
  },
  {
    id: 'whisperx',
    name: 'WhisperX',
    repo: 'https://github.com/m-bain/whisperX',
    license: 'BSD-2-Clause',
    role: '中文 ASR、VAD 和字符/词级对齐。模型许可单独记录。',
    integration: 'recommended-adapter',
  },
  {
    id: 'mfa',
    name: 'Montreal Forced Aligner',
    repo: 'https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner',
    license: 'MIT',
    role: '疑难语音、phone/viseme 与精细口型对齐。',
    integration: 'optional-precision',
  },
  {
    id: 'hyperframes-transcribe',
    name: 'HyperFrames Transcribe',
    repo: 'https://github.com/heygen-com/hyperframes',
    license: 'Apache-2.0',
    role: '当前项目已记录的最终 WAV 转写入口，后续可替换为 WhisperX adapter。',
    integration: 'base-asr-only',
  },
  {
    id: 'elkjs',
    name: 'ELK.js',
    repo: 'https://github.com/kieler/elkjs',
    license: 'EPL-2.0',
    role: 'Graph IR 自动布局并保留节点与边 ID。',
    integration: 'ready',
  },
  {
    id: 'react-flow',
    name: 'React Flow',
    repo: 'https://github.com/xyflow/xyflow',
    license: 'MIT',
    role: '用于 SOP 工作流节点编辑和 Graph IR 布局微调；只写节点坐标，不改节点、边或事实文案。',
    integration: 'ready-position-only',
  },
  {
    id: 'mermaid',
    name: 'Mermaid',
    repo: 'https://github.com/mermaid-js/mermaid',
    license: 'MIT',
    role: '低成本流程图 DSL；进入动画前必须注入 canonical ID。',
    integration: 'optional-fast-path',
  },
  {
    id: 'hyperframes',
    name: 'HyperFrames',
    repo: 'https://github.com/heygen-com/hyperframes',
    license: 'Apache-2.0',
    role: '唯一主视频内核：composition、Studio、check、snapshot、preview 和 render。',
    integration: 'ready',
    resolvedVersion: '0.7.77',
  },
  {
    id: 'ffmpeg',
    name: 'FFmpeg / ffprobe',
    repo: 'https://github.com/FFmpeg/FFmpeg',
    license: 'LGPL/GPL depends on build',
    role: '编解码、黑帧、静音、响度、True Peak 和完整解码检查。',
    integration: 'delivery-qa-adapter',
  },
  {
    id: 'subtitle-edit',
    name: 'Subtitle Edit',
    repo: 'https://github.com/SubtitleEdit/subtitleedit',
    license: 'MIT',
    role: 'Windows 字幕波形、CPS、断句和 SRT/ASS 人工终审。',
    integration: 'manual-review',
  },
  {
    id: 'subtitle-qa',
    name: 'AutoVideo Subtitle QA',
    repo: null,
    license: 'project-local adapter',
    role: '复用锁定 alignment.cues 和 SRT 做确定性字幕机器 QA；不替代人工语义审校或 OCR。',
    integration: 'ready-machine-plus-human-gates',
  },
  {
    id: 'subtitle-review',
    name: 'AutoVideo Subtitle Human Review',
    repo: null,
    license: 'project-local adapter',
    role: '逐 cue 审校字幕语义、术语、断句、标点和时间可读性，并把人工批准绑定到当前 subtitle QA、alignment 与 SRT。',
    integration: 'ready',
  },
  {
    id: 'paddleocr',
    name: 'PaddleOCR',
    repo: 'https://github.com/PaddlePaddle/PaddleOCR',
    license: 'Apache-2.0',
    role: '关键帧中文 OCR，检查屏幕文字缺失、错误和溢出。',
    integration: 'model-source-via-rapidocr',
  },
  {
    id: 'rapidocr',
    name: 'RapidOCR ONNXRuntime',
    repo: 'https://github.com/RapidAI/RapidOCR',
    license: 'Apache-2.0',
    role: '复用 PaddleOCR 中文模型，以本地 CPU ONNX 运行时生成逐帧文字、置信度和坐标的哈希绑定回执。',
    integration: 'ready-local-adapter',
  },
  {
    id: 'screen-text-review',
    name: 'AutoVideo Screen Text Review',
    repo: null,
    license: 'project-local adapter',
    role: '在当前 HyperFrames composition 上逐帧复核字幕安全区、遮挡、屏幕文字正确性、对比度和重复信息；OCR 不可用时强制记录人工替代。',
    integration: 'ready-manual-fallback',
  },
  {
    id: 'visual-variety-qa',
    name: 'AutoVideo Visual Variety QA',
    repo: null,
    license: 'project-local adapter',
    role: '检查视觉载体、动效配方、文字压缩、连续重复和 Graph IR 绑定，防止全片退化为纯文字 PPT。',
    integration: 'ready',
  },
  {
    id: 'pyscenedetect',
    name: 'PySceneDetect',
    repo: 'https://github.com/Breakthrough/PySceneDetect',
    license: 'BSD-3-Clause',
    role: '交付母版的意外切镜和镜头边界回归检查。',
    integration: 'planned-qa',
  },
  {
    id: 'standard-delivery-package',
    name: 'AutoVideo 标准交付包装配器',
    repo: null,
    license: 'project-local adapter',
    role: '把正式项目、工作台快照、可编辑 HyperFrames 源码、QA 和全过程记录装配为可校验交付目录。',
    integration: 'ready',
  },
];

export const stageAppliesToProject = (definition, project) => Boolean(
  definition
  && (definition.custom || !definition.routes || definition.routes.includes(project.route))
  && (!definition.voiceRoutes || definition.voiceRoutes.includes(project.voiceRoute)),
);

export const workflowStages = [
  {
    id: 'source-register',
    routes: ['materials', 'script', 'audio'],
    group: 'content',
    title: '素材登记',
    description: '登记文件、网页、图片和音视频的来源、SHA-256、时间与版权边界。',
    artifact: 'sources.json',
    generator: 'source-index',
    defaultTool: 'local-source-index',
    tools: ['local-source-index', 'open-notebook', 'ragflow'],
    executableTools: ['local-source-index'],
    humanGate: false,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'ready',
    tutorial: 'docs/10-讲解视频规模化SOP.md',
  },
  {
    id: 'audio-transcript',
    routes: ['audio'],
    group: 'content',
    title: '口播录音转写',
    description: '对原口播做 ASR，生成可校订文本；不能把未经人工检查的识别结果直接锁稿。',
    artifact: 'transcript.draft.json',
    generator: 'transcribe-source',
    defaultTool: 'hyperframes-transcribe',
    tools: ['hyperframes-transcribe', 'whisperx'],
    executableTools: ['hyperframes-transcribe'],
    humanGate: false,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'ready-with-adapter',
    tutorial: 'docs/11-CosyVoice14与HyperFrames最终视频教程.md',
  },
  {
    id: 'material-suitability',
    routes: ['materials', 'script'],
    group: 'content',
    title: 'Content suitability',
    description: 'Diagnose whether registered material can enter spoken rewriting and record preparation actions.',
    artifact: 'material-suitability.json',
    generator: 'material-suitability',
    defaultTool: 'local-source-index',
    tools: ['local-source-index'],
    executableTools: ['local-source-index'],
    humanGate: false,
    manualApproval: true,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'docs/17-批量内容入口与创意配方SOP.md',
  },
  {
    id: 'evidence-ledger',
    routes: ['materials', 'script'],
    group: 'content',
    title: '事实与观点台账',
    description: '事实、观点、争议和缺口分开；每个事实绑定逐字引句和来源定位。',
    artifact: 'evidence.json',
    generator: 'codex-evidence',
    defaultTool: 'codex-cli',
    tools: ['codex-cli', 'open-notebook', 'storm', 'gpt-researcher', 'ragflow'],
    executableTools: ['codex-cli'],
    humanGate: true,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'adapter-ready',
    tutorial: 'docs/10-讲解视频规模化SOP.md',
  },
  {
    id: 'script-draft',
    routes: ['materials'],
    group: 'content',
    title: 'Narration Writer',
    description: '只消费当前 Evidence 与 Outline，按稳定 section/claim/source ID 生成口播初稿。',
    artifact: 'script.draft.json',
    generator: 'codex-script',
    defaultTool: 'codex-cli',
    tools: ['codex-cli', 'promptfoo'],
    executableTools: ['codex-cli'],
    humanGate: false,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'adapter-ready',
    tutorial: 'docs/10-讲解视频规模化SOP.md',
  },
  {
    id: 'content-outline',
    routes: ['materials'],
    group: 'content',
    title: 'Outline Planner',
    description: '把批准 Evidence 与项目 brief 转成有时长、claim/source 和屏幕意图的结构化大纲，不写最终口播。',
    artifact: 'content-outline.json',
    generator: 'content-outline',
    defaultTool: 'codex-cli',
    tools: ['codex-cli', 'promptfoo'],
    executableTools: ['codex-cli'],
    humanGate: false,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'ready-with-contract',
    tutorial: 'tools/content-pipeline/README.md',
  },
  {
    id: 'spoken-rewrite',
    routes: ['materials', 'script'],
    group: 'content',
    title: 'Spoken rewrite',
    description: 'Turn source material into natural Mandarin speech with claim, source, and screen-summary bindings.',
    artifact: 'spoken-rewrite.json',
    generator: 'spoken-rewrite',
    defaultTool: 'codex-cli',
    tools: ['codex-cli'],
    executableTools: ['codex-cli'],
    humanGate: false,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'adapter-ready',
    tutorial: 'docs/17-批量内容入口与创意配方SOP.md',
  },
  {
    id: 'claim-source-review',
    routes: ['materials', 'script'],
    group: 'content',
    title: 'Claim/source review',
    description: 'Verify exact quotes, claim bindings, and source hashes before wording approval.',
    artifact: 'claim-source-review.json',
    generator: 'claim-source-review',
    defaultTool: 'local-source-index',
    tools: ['local-source-index'],
    executableTools: ['local-source-index'],
    humanGate: false,
    manualApproval: true,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'docs/17-批量内容入口与创意配方SOP.md',
  },
  {
    id: 'content-duration-fit',
    routes: ['materials', 'script'],
    group: 'content',
    title: 'Duration Fitter',
    description: '以固定文本密度规则检查总时长和分段预算；只给返工问题，不静默改字，之后再运行 final Claim Verifier。',
    artifact: 'content-duration-fit.json',
    generator: 'content-duration-fit',
    defaultTool: 'local-source-index',
    tools: ['local-source-index', 'promptfoo'],
    executableTools: ['local-source-index'],
    humanGate: false,
    manualApproval: true,
    artifactEditable: false,
    maturity: 'ready-text-budget-only',
    tutorial: 'tools/content-pipeline/README.md',
  },
  {
    id: 'script-review',
    routes: ['materials', 'script', 'audio'],
    group: 'content',
    title: '口播稿人工微调',
    description: '只在稿件、术语和时长上做小范围调整；批准后形成唯一可朗读文字。',
    artifact: 'script.approved.txt',
    generator: 'script-review',
    defaultTool: 'codex-cli',
    tools: ['codex-cli', 'promptfoo'],
    executableTools: ['codex-cli'],
    humanGate: true,
    artifactEditable: true,
    maturity: 'ready',
    tutorial: 'docs/11-CosyVoice14与HyperFrames最终视频教程.md',
  },
  {
    id: 'content-approval',
    routes: ['materials', 'script'],
    group: 'content',
    title: 'Content approval receipt',
    description: 'Freeze the human-approved narration and its complete hash-bound content chain.',
    artifact: 'content-approval.json',
    generator: 'content-approval',
    defaultTool: 'local-source-index',
    tools: ['local-source-index'],
    executableTools: ['local-source-index'],
    humanGate: true,
    manualApproval: true,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'docs/17-批量内容入口与创意配方SOP.md',
  },
  {
    id: 'narration-lock',
    routes: ['materials', 'script', 'audio'],
    group: 'audio',
    title: 'NarrationLock',
    description: '调用项目现有 video:new，冻结批准文字、SHA-256、比例、平台和审批状态。',
    artifact: 'NarrationLock.json',
    generator: 'video-init',
    defaultTool: 'codex-cli',
    tools: ['codex-cli'],
    executableTools: ['codex-cli'],
    humanGate: false,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'hyperframes-workflow-kit/VOICE_HANDOFF.md',
  },
  {
    id: 'template-lock',
    routes: ['materials', 'script', 'audio'],
    group: 'audio',
    title: '正式模板锁定',
    description: '调用 video:apply-template 套用已批准的 modern-ip-host-explainer 项目样式，并冻结版本、配色、比例与源文件哈希。',
    artifact: 'template-lock.json',
    generator: 'apply-template',
    defaultTool: 'codex-cli',
    tools: ['codex-cli'],
    executableTools: ['codex-cli'],
    humanGate: false,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'style-library/styles/project/modern-ip-host-explainer/USAGE.md',
  },
  {
    id: 'pronunciation-review',
    routes: ['materials', 'script', 'audio'],
    voiceRoutes: ['preset14'],
    group: 'audio',
    title: '中英混读上下文探针',
    description: '扫描全部拉丁 token，按缩写、英文词、品牌、版本与代码标识分类；为主观术语生成 2-3 个原句上下文候选，逐个试听并选择后才生成 effective 词表。',
    artifact: 'qa/pronunciation-approval.json',
    generator: 'pronunciation-probes',
    defaultTool: 'cosyvoice14',
    tools: ['cosyvoice14'],
    executableTools: ['cosyvoice14'],
    humanGate: true,
    manualApproval: false,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'hyperframes-workflow-kit/VOICE_HANDOFF.md',
  },
  {
    id: 'voice-final',
    routes: ['materials', 'script', 'audio'],
    group: 'audio',
    title: '配音候选 A/B 与正式晋升',
    description: '使用预设 14 或明确覆盖的声音路线生成版本化候选 WAV，不覆盖现有正式音轨；逐个完整听审并选择后，才原子晋升为唯一 narration.final.wav。',
    artifact: 'audio/voice-candidates/<candidate-id>/candidate.json',
    generator: 'cosyvoice',
    defaultTool: 'cosyvoice14',
    tools: ['cosyvoice14'],
    executableTools: ['cosyvoice14'],
    humanGate: true,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'docs/11-CosyVoice14与HyperFrames最终视频教程.md',
  },
  {
    id: 'audio-align',
    routes: ['materials', 'script', 'audio'],
    group: 'audio',
    title: '最终音频基础时间戳',
    description: '用固定 Whisper small 生成基础时间戳，映射回 NarrationLock，并产出哈希绑定的 alignment、SRT、alignment validation 与音频 QA；精确中文 forced alignment 仍需接入 WhisperX。',
    artifact: 'audio/alignment.json',
    generator: 'transcribe',
    defaultTool: 'hyperframes-transcribe',
    tools: ['hyperframes-transcribe', 'whisperx', 'mfa'],
    executableTools: ['hyperframes-transcribe'],
    humanGate: false,
    artifactEditable: false,
    maturity: 'partial-base-asr',
    tutorial: 'hyperframes-workflow-kit/VOICE_HANDOFF.md',
  },
  {
    id: 'subtitle-qa',
    routes: ['materials', 'script', 'audio'],
    group: 'audio',
    title: '字幕与画面文字 QA',
    description: '复用锁定 alignment.cues 和 SRT，检查字幕时间轴、逐字一致性、CPS、重复/缺失 cue；人工语义审校与 OCR 仍保持独立待审门禁。',
    artifact: 'qa/subtitle-qa.json',
    generator: 'subtitle-qa',
    defaultTool: 'subtitle-qa',
    tools: ['subtitle-qa', 'subtitle-edit', 'paddleocr'],
    executableTools: ['subtitle-qa'],
    humanGate: false,
    manualApproval: false,
    artifactEditable: false,
    maturity: 'ready-machine-plus-human-gates',
    tutorial: 'docs/12-AutoVideo标准生产Runbook.md',
  },
  {
    id: 'subtitle-review',
    routes: ['materials', 'script', 'audio'],
    group: 'audio',
    title: '字幕语义人工审校',
    description: '逐 cue 确认语义、术语、断句、标点和时间可读性；批准回执绑定当前 subtitle-qa、alignment 与 SRT，任何上游变化都会失效。',
    artifact: 'qa/subtitle-human-approval.json',
    generator: 'subtitle-review',
    defaultTool: 'subtitle-review',
    tools: ['subtitle-review', 'subtitle-edit'],
    executableTools: ['subtitle-review'],
    humanGate: true,
    manualApproval: false,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'docs/12-AutoVideo标准生产Runbook.md',
  },
  {
    id: 'visual-plan',
    routes: ['materials', 'script', 'audio'],
    group: 'visual',
    title: '语义节拍与分镜',
    description: '先按 NarrationLock、alignment 和模板机器合同生成确定性 storyboard/shot/Graph IR；LLM 只可作为经过审查的可选 enrichment。',
    artifact: 'plan/storyboard.json',
    generator: 'deterministic-planning',
    defaultTool: 'deterministic-planning',
    tools: ['deterministic-planning', 'codex-cli', 'promptfoo'],
    executableTools: ['deterministic-planning'],
    humanGate: true,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'adapter-ready',
    tutorial: 'docs/10-讲解视频规模化SOP.md',
  },
  {
    id: 'diagram-assets',
    routes: ['materials', 'script', 'audio'],
    group: 'visual',
    title: '流程图与素材计划',
    description: 'Graph IR 经 ELK.js 自动布局；React Flow 可视化编辑器只允许拖动节点，保存后通过 graph-layout SHA 绑定进入正式编译。',
    artifact: 'plan/graph-layout.json',
    generator: 'elk-layout',
    defaultTool: 'elkjs',
    tools: ['elkjs', 'react-flow', 'mermaid'],
    executableTools: ['elkjs', 'react-flow'],
    humanGate: false,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'ready-visual-layout-editor',
    tutorial: 'docs/research/可编辑画板与SVG组件调研.md',
  },
  {
    id: 'style-probe',
    routes: ['materials', 'script', 'audio'],
    group: 'visual',
    title: '风格与节奏探针',
    description: '使用同一最终音频窗口生成一张静帧与 3-8 秒探针，批准后才可全片制作。',
    artifact: 'STYLE_REVIEW.md',
    generator: 'style-probe',
    defaultTool: 'hyperframes',
    tools: ['hyperframes', 'codex-cli'],
    executableTools: ['hyperframes'],
    humanGate: true,
    artifactEditable: true,
    maturity: 'ready',
    tutorial: 'style-library/styles/project/modern-ip-host-explainer/USAGE.md',
  },
  {
    id: 'visual-variety-qa',
    routes: ['materials', 'script', 'audio'],
    group: 'visual',
    title: '视觉多样性 QA',
    description: '检查视觉载体与配方分布、连续重复、屏幕摘要压缩、图解 Graph IR 绑定和资产型载体来源，阻止全片退化为纯文字 PPT。',
    artifact: 'qa/visual-variety-qa.json',
    generator: 'visual-variety-qa',
    defaultTool: 'visual-variety-qa',
    tools: ['visual-variety-qa', 'hyperframes'],
    executableTools: ['visual-variety-qa'],
    humanGate: false,
    manualApproval: false,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'docs/16-高级动效库与开源组合路线.md',
  },
  {
    id: 'rights-clearance',
    routes: ['materials', 'script', 'audio'],
    group: 'video',
    title: '素材与发布权利清单',
    description: '以 publication-rights/v2 登记 source、voice、template、media 与 AssetManifest 的实际 SHA；公开清权必须绑定本地凭据，内部使用保留公开发布阻塞。',
    artifact: 'receipts/publication-rights.json',
    generator: 'rights-ledger',
    defaultTool: 'local-source-index',
    tools: ['local-source-index', 'cosyvoice14', 'hyperframes', 'ffmpeg'],
    executableTools: ['local-source-index'],
    humanGate: true,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'ready-v2-evidence-bound',
    tutorial: 'hyperframes-workflow-kit/AUTOVIDEO_HANDOFF.md',
  },
  {
    id: 'audio-handoff',
    routes: ['materials', 'script', 'audio'],
    group: 'video',
    title: '正式音频交接',
    description: '调用 video:attach-audio，把已批准的最终 WAV、alignment、配音 recipe 与权利状态写入正式 audio-handoff.json。',
    artifact: 'audio-handoff.json',
    generator: 'audio-handoff',
    defaultTool: 'codex-cli',
    tools: ['codex-cli'],
    executableTools: ['codex-cli'],
    humanGate: false,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'hyperframes-workflow-kit/AUTOVIDEO_HANDOFF.md',
  },
  {
    id: 'composition-readiness',
    routes: ['materials', 'script', 'audio'],
    group: 'video',
    title: '全片制作就绪检查',
    description: '实时运行 video:template-status；公开路径必须 readyForComposition=true，仅内部路径只可在全部技术检查通过且公开发布继续阻塞时进入制作。',
    artifact: 'composition-readiness.json',
    generator: 'template-status',
    defaultTool: 'codex-cli',
    tools: ['codex-cli'],
    executableTools: ['codex-cli'],
    humanGate: false,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'hyperframes-workflow-kit/AUTOVIDEO_HANDOFF.md',
  },
  {
    id: 'full-production',
    routes: ['materials', 'script', 'audio'],
    group: 'video',
    title: 'HyperFrames 全片制作',
    description: '根据批准分镜、素材、最终音频与模板生成唯一 16:9 composition；工作台画面微调通过稳定 scene/cue/object ID 写入 overrides 后局部重编译。',
    artifact: 'production/hyperframes/index.html',
    generator: 'full-production-compile',
    defaultTool: 'hyperframes',
    tools: ['hyperframes', 'codex-cli'],
    executableTools: ['hyperframes'],
    humanGate: false,
    artifactEditable: false,
    maturity: 'ready-with-overrides',
    tutorial: 'docs/15-连续讲解模板与工作台操作手册.md',
  },
  {
    id: 'qa-review',
    routes: ['materials', 'script', 'audio'],
    group: 'video',
    title: 'HyperFrames 结构与视觉检查',
    description: '运行固定版本 HyperFrames check --strict；最终 MP4 的解码、响度、黑帧与静音在渲染后单独检查。',
    artifact: 'qa/report.json',
    generator: 'quality-check',
    defaultTool: 'hyperframes',
    tools: ['hyperframes', 'ffmpeg', 'paddleocr', 'subtitle-edit'],
    executableTools: ['hyperframes'],
    humanGate: false,
    artifactEditable: false,
    maturity: 'ready-structure-only',
    tutorial: 'hyperframes-workflow-kit/03-质量检查清单.md',
  },
  {
    id: 'screen-text-review',
    routes: ['materials', 'script', 'audio'],
    group: 'video',
    title: '成片屏幕文字与 OCR 复核',
    description: '绑定当前 composition、HyperFrames check、字幕人工批准和关键抽帧，检查字幕安全区、遮挡、文字准确性、对比度与重复信息；无 OCR 时必须显式采用人工替代。',
    artifact: 'qa/screen-text-human-approval.json',
    generator: 'screen-text-review',
    defaultTool: 'screen-text-review',
    tools: ['screen-text-review', 'rapidocr', 'paddleocr', 'subtitle-edit'],
    executableTools: ['screen-text-review'],
    humanGate: true,
    manualApproval: false,
    artifactEditable: false,
    maturity: 'ready-ocr-plus-manual-fallback',
    tutorial: 'docs/12-AutoVideo标准生产Runbook.md',
  },
  {
    id: 'final-preview',
    routes: ['materials', 'script', 'audio'],
    group: 'delivery',
    title: 'Studio 最终预览',
    description: '完整音画在 HyperFrames Studio 预览；批准记录绑定 composition hash。',
    artifact: 'receipts/final-preview.json',
    generator: 'preview-receipt',
    defaultTool: 'hyperframes',
    tools: ['hyperframes'],
    executableTools: ['hyperframes'],
    humanGate: true,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'docs/15-连续讲解模板与工作台操作手册.md',
  },
  {
    id: 'render-deliver',
    routes: ['materials', 'script', 'audio'],
    group: 'delivery',
    title: '高质量渲染与交付包',
    description: '仅消费已批准且哈希未变化的 Studio 预览；已清权输出 master，internal-only 只输出明确标记且禁止公开发布的 review MP4。',
    artifact: 'receipts/delivery.json',
    generator: 'hyperframes-render',
    defaultTool: 'hyperframes',
    tools: ['hyperframes', 'ffmpeg'],
    executableTools: ['hyperframes'],
    humanGate: false,
    artifactEditable: false,
    maturity: 'master-only',
    tutorial: 'docs/11-CosyVoice14与HyperFrames最终视频教程.md',
  },
  {
    id: 'delivery-qa',
    routes: ['materials', 'script', 'audio'],
    group: 'delivery',
    title: '交付母版媒体 QA',
    description: '对最终 MP4 运行 ffprobe、完整解码、黑帧、静音和 EBU R128 响度检查，输出机器回执。',
    artifact: 'qa/delivery-report.json',
    generator: 'delivery-qa',
    defaultTool: 'ffmpeg',
    tools: ['ffmpeg', 'pyscenedetect', 'paddleocr', 'subtitle-edit'],
    executableTools: ['ffmpeg'],
    humanGate: false,
    artifactEditable: false,
    maturity: 'ready-core-media',
    tutorial: 'hyperframes-workflow-kit/03-质量检查清单.md',
  },
  {
    id: 'retrospective',
    routes: ['materials', 'script', 'audio'],
    group: 'delivery',
    title: '复盘与模板回写',
    description: '记录成功组件、失败模式、人工修改和用户反馈；验证后再升级项目模板。',
    artifact: 'RETROSPECTIVE.md',
    generator: 'retrospective',
    defaultTool: 'codex-cli',
    tools: ['codex-cli', 'promptfoo'],
    executableTools: ['codex-cli'],
    humanGate: true,
    manualApproval: true,
    artifactEditable: true,
    maturity: 'adapter-ready',
    tutorial: 'hyperframes-workflow-kit/04-复盘规则.md',
  },
  {
    id: 'package-export',
    routes: ['materials', 'script', 'audio'],
    group: 'delivery',
    title: '标准交付包装配',
    description: '将当前正式项目、工作台审计快照、可编辑 HyperFrames 源码和逐文件哈希清单装配为可复用交付包。',
    artifact: 'delivery/standard-package/PACKAGE_STATUS.json',
    generator: 'standard-delivery-package',
    defaultTool: 'standard-delivery-package',
    tools: ['standard-delivery-package'],
    executableTools: ['standard-delivery-package'],
    humanGate: false,
    manualApproval: false,
    artifactEditable: false,
    maturity: 'ready',
    tutorial: 'docs/14-标准交付包装配与验证.md',
  },
];

export const canonicalStageOrder = [
  'source-register',
  'audio-transcript',
  'material-suitability',
  'evidence-ledger',
  'content-outline',
  'script-draft',
  'spoken-rewrite',
  'content-duration-fit',
  'claim-source-review',
  'script-review',
  'content-approval',
  'narration-lock',
  'template-lock',
  'pronunciation-review',
  'voice-final',
  'audio-align',
  'subtitle-qa',
  'subtitle-review',
  'rights-clearance',
  'audio-handoff',
  'visual-plan',
  'diagram-assets',
  'style-probe',
  'visual-variety-qa',
  'composition-readiness',
  'full-production',
  'qa-review',
  'screen-text-review',
  'final-preview',
  'render-deliver',
  'delivery-qa',
  'retrospective',
  'package-export',
];

const stageRank = new Map(canonicalStageOrder.map((id, index) => [id, index]));
workflowStages.sort((left, right) => stageRank.get(left.id) - stageRank.get(right.id));

export const groups = [
  {id: 'content', label: '内容与事实'},
  {id: 'audio', label: '配音与时间'},
  {id: 'visual', label: '图解与风格'},
  {id: 'video', label: 'HyperFrames 制作'},
  {id: 'delivery', label: '预览与交付'},
];

export const getTool = (id) => toolRegistry.find((tool) => tool.id === id) ?? null;
export const getStage = (id) => workflowStages.find((stage) => stage.id === id) ?? null;
